In [29]:
import numpy as np
import pandas as pd
import re
import nltk
import spacy
import string
import openpyxl
import itertools
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
chat_words_str = """
DM=Direct message
CT=Cuttweet
RT=Retweet
PRT=Partial retweet
MT=Modified tweet
PRT=Please retweet
HT=Hat tip
CC=Carbon-copy
CX=Correction
EM=Email Marketing
SEO=Search Engine Optimization
SROI=Social Return on Investment
SN=Social Network
YT=YouTube
UGC=User-Generated Content
SMO=Social Media Optimization
FB=Facebook
LI=LinkedIn
SM=Social Media
SMM=Social Media Marketing
EZine=Electronic Magazine
BGD=Background
CD9=Code 9, parents are around
BTW=By the way
AB=About
ABT=About
DD=Dear daughter
AFAIK=far as I know
AYFKMWTS=Are you f—ing kidding me with this s—?
BR=Best regards
CHK=Check
CUL8R=See you later
DP=used to mean “profile pic”
FML=F— my life
FUBAR=F—ed up beyond all repair (slang from the US Military)
BBFN=Bye for now
B4=Before
DS=Dear son
FF=Follow Friday
EMA=Email address
DYK=Do you know
F2F=Face to face
FTF=Face to face
HAGN=Have a good night
DF=Dear fiancé
DAM=Don’t annoy me
FFS=For F—‘s Sake
EM=Email
EML=Email
FOTD=Find of the day
FTW=For the win, F— the world
FWIW=For what it’s worth
HTH=Hope that helps
GMAFB=Give me a f—ing break
HAND=Have a nice day
ICYMI=In case you missed it
GTFOOH=Get the f— out of here
GTS=Guess the song
HOTD=Headline of the day
IIRC=If I remember correctly
KYSO=Knock your socks off
KK=Kewl kewl, or ok, got it
HT=Head through
IC=I see
IDK=I don’t know
LHH=hella hard
ZOMG=OMG to the max
IMHO=In my humble opinion
NFW=No f—ing way
ORLY=Oh, really?
YOYO=You’re on your own
LMAO=Laughing my ass off
IRL=In real life
JK=Just kidding
JV=Joint venture
LO=Little One
LOL=Laugh out loud
MM=Music Monday
LMK=Let me know
TY=Thank you
SRS=Serious
STF=Shut the f—
STFU=Shut the f— up!
TL=Timeline
TYIA=Thank you in advance
TT=Trending topic
TYVW=Thank you very much
BRB=Be Right Back
AFAIK=As Far As I Know
AFK=Away From Keyboard
ASAP=As Soon As Possible
ATK=At The Keyboard
ATM=At The Moment
A3=Anytime, Anywhere, Anyplace
BAK=Back At Keyboard
BBL=Be Back Later
BBS=Be Back Soon
BFN=Bye For Now
B4N=Bye For Now
BRB=Be Right Back
BRT=Be Right There
BTW=By The Way
B4=Before
B4N=Bye For Now
CU=See You
CUL8R=See You Later
CYA=See You
FAQ=Frequently Asked Questions
FC=Fingers Crossed
FWIW=For What It's Worth
FYI=For Your Information
GAL=Get A Life
GG=Good Game
GN=Good Night
GMTA=Great Minds Think Alike
GR8=Great!
G9=Genius
IC=I See
ICQ=I Seek you (also a chat program)
ILU=ILU: I Love You
IMHO=In My Honest Opinion
IMO=In My Opinion
IOW=In Other Words
IRL=In Real Life
KISS=Keep It Simple, Stupid
LDR=Long Distance Relationship
LMAO=Laugh My A.. Off
LOL=Laughing Out Loud
LTNS=Long Time No See
L8R=Later
MTE=My Thoughts Exactly
M8=Mate
NRN=No Reply Necessary
OIC=Oh I See
PITA=Pain In The A..
PRT=Party
SFW=Safe for work
TY=Thank you
TMB=Tweet me back
BRB=Be Right Back
IMO=In My Opinion
RLRT=Real-life re-tweet, a close cousin to OH
OOMF=One of my friends/followers
NTS=Note to self
RTFM=Read the f—ing manual
SNAFU=Situation normal, all f—ed up (slang from the US Military)
RLRT=Real-life re-tweet, a close cousin to OH
SMH=Shaking my head
STFW=Search the f—ing web!
TFTT=Thanks for this tweet
SOB=Son of a B—-
TFTF=Thanks for the follow
PRW=Parents Are Watching
ROFL=Rolling On The Floor Laughing
ROFLOL=Rolling On The Floor Laughing Out Loud
ROTFLMAO=Rolling On The Floor Laughing My A.. Off
SK8=Skate
STATS=Your sex and age
ASL=Age, Sex, Location
THX=Thank You
TTFN=Ta-Ta For Now!
TTYL=Talk To You Later
U=You
U2=You Too
U4E=Yours For Ever
WB=Welcome Back
WTF=What The F...
WTG=Way To Go!
WUF=Where Are You From?
W8=Wait...
7K=Sick:-D Laugher
"""

# Data preprocessing

In [31]:
df = pd.read_excel("template.xlsx")

## Chat Words Conversion

In [32]:
chat_words_map_dict = {}
chat_words_list = []
for line in chat_words_str.split("\n"):
    if line != "":
        cw = line.split("=")[0]
        cw_expanded = line.split("=")[1]
        chat_words_list.append(cw)
        chat_words_map_dict[cw] = cw_expanded
chat_words_list = set(chat_words_list)


def chat_words_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words_list:
            new_text.append(chat_words_map_dict[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)


df["text_chat_conversion"] = df["text"].apply(lambda text: chat_words_conversion(text))
df

text  \
0      The cars drive, fast and erratically   
1                       the car drive slow?   
2  The bike ride very fast and erratically!   

                       text_chat_conversion  
0      The cars drive, fast and erratically  
1                       the car drive slow?  
2  The bike ride very fast and erratically!

## Spelling correction

In [33]:
from spellchecker import SpellChecker

spell = SpellChecker()


def correct_spellings(text):
    corrected_text = []
    misspelled_words = spell.unknown(text.split())
    for word in text.split():
        if word in misspelled_words:
            corrected_text.append(spell.correction(word))
        else:
            corrected_text.append(word)
    return " ".join(corrected_text)


df["correct_spellings"] = df["text_chat_conversion"].apply(lambda text: correct_spellings(text))
df

text  \
0      The cars drive, fast and erratically   
1                       the car drive slow?   
2  The bike ride very fast and erratically!   

                       text_chat_conversion  \
0      The cars drive, fast and erratically   
1                       the car drive slow?   
2  The bike ride very fast and erratically!   

                         correct_spellings  
0      The cars drive fast and erratically  
1                       the car drive slow  
2  The bike ride very fast and erratically

## Punctuation removal

In [34]:
PUNCT_TO_REMOVE = string.punctuation


def remove_punctation(text):
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))


df["text_punctation_remove"] = df["text_chat_conversion"].apply(lambda text: remove_punctation(text))
df["text_lower"] = df["text_punctation_remove"].str.lower()
df

text  \
0      The cars drive, fast and erratically   
1                       the car drive slow?   
2  The bike ride very fast and erratically!   

                       text_chat_conversion  \
0      The cars drive, fast and erratically   
1                       the car drive slow?   
2  The bike ride very fast and erratically!   

                         correct_spellings  \
0      The cars drive fast and erratically   
1                       the car drive slow   
2  The bike ride very fast and erratically   

                    text_punctation_remove  \
0      The cars drive fast and erratically   
1                       the car drive slow   
2  The bike ride very fast and erratically   

                                text_lower  
0      the cars drive fast and erratically  
1                       the car drive slow  
2  the bike ride very fast and erratically

## Stop Words removal

In [35]:
from nltk.corpus import stopwords

", ".join(stopwords.words('english'))

"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mus

In [36]:
STOPWORDS = set(stopwords.words('english'))


def remove_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])


df["text_stopwords_removal"] = df["text_lower"].apply(lambda text: remove_stopwords(text))
df.T

0  \
text                    The cars drive, fast and erratically   
text_chat_conversion    The cars drive, fast and erratically   
correct_spellings        The cars drive fast and erratically   
text_punctation_remove   The cars drive fast and erratically   
text_lower               the cars drive fast and erratically   
text_stopwords_removal           cars drive fast erratically   

                                          1  \
text                    the car drive slow?   
text_chat_conversion    the car drive slow?   
correct_spellings        the car drive slow   
text_punctation_remove   the car drive slow   
text_lower               the car drive slow   
text_stopwords_removal       car drive slow   

                                                               2  
text                    The bike ride very fast and erratically!  
text_chat_conversion    The bike ride very fast and erratically!  
correct_spellings        The bike ride very fast and erratically  
text_punctation_remove   The bike ride very fast and erratically  
text_lower               the bike ride very fast and erratically  
text_stopwords_removal                bike ride fast erratically

## Freq and rare words

In [37]:
# from collections import Counter
# cnt = Counter()
# for text in df["text_stopwords_removal"].values:
#     for word in text.split():
#         cnt[word] += 1
#
# cnt.most_common(10)

In [38]:
# FREQWORDS = set([w for (w, wc) in cnt.most_common(10)])
# def remove_freqwords(text):
#     """custom function to remove the frequent words"""
#     return " ".join([word for word in str(text).split() if word not in FREQWORDS])
#
# df["text_wo_stopfreq"] = df["text_wo_stop"].apply(lambda text: remove_freqwords(text))
# df.head()

In [39]:
# n_rare_words = 10
# RAREWORDS = set([w for (w, wc) in cnt.most_common()[:-n_rare_words-1:-1]])
# def remove_rarewords(text):
#     """custom function to remove the rare words"""
#     return " ".join([word for word in str(text).split() if word not in RAREWORDS])
#
# df["text_wo_stopfreqrare"] = df["text_wo_stopfreq"].apply(lambda text: remove_rarewords(text))
# df.head()

## Stemming

In [40]:
from nltk.stem.porter import PorterStemmer

# Drop the two columns
stemmer = PorterStemmer()


def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])


df["text_stemmed"] = df["text_stopwords_removal"].apply(lambda text: stem_words(text))

In [41]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()


def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])


df["text_preprocessed"] = df["text_stopwords_removal"].apply(lambda text: lemmatize_words(text))


In [42]:
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
wordnet_map = {"N": wordnet.NOUN, "V": wordnet.VERB, "J": wordnet.ADJ, "R": wordnet.ADV}


def lemmatize_words(text):
    pos_tagged_text = nltk.pos_tag(text.split())
    return " ".join(
        [lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_tagged_text])


df["text_lemmatized_with_pos"] = df["correct_spellings"].apply(lambda text: lemmatize_words(text))
df.head()


text  \
0      The cars drive, fast and erratically   
1                       the car drive slow?   
2  The bike ride very fast and erratically!   

                       text_chat_conversion  \
0      The cars drive, fast and erratically   
1                       the car drive slow?   
2  The bike ride very fast and erratically!   

                         correct_spellings  \
0      The cars drive fast and erratically   
1                       the car drive slow   
2  The bike ride very fast and erratically   

                    text_punctation_remove  \
0      The cars drive fast and erratically   
1                       the car drive slow   
2  The bike ride very fast and erratically   

                                text_lower       text_stopwords_removal  \
0      the cars drive fast and erratically  cars drive fast erratically   
1                       the car drive slow               car drive slow   
2  the bike ride very fast and erratically   bike ride fast erratically   

           text_stemmed           text_preprocessed  \
0  car drive fast errat  car drive fast erratically   
1        car drive slow              car drive slow   
2  bike ride fast errat  bike ride fast erratically   

                  text_lemmatized_with_pos  
0       The car drive fast and erratically  
1                       the car drive slow  
2  The bike ride very fast and erratically

In [43]:
## Emoji and emoticons removal/conversion

In [44]:
# Reference : https://gist.github.com/slowkow/7a7f61f495e3dbb7e3d767f97bd7304b
# def remove_emoji(string):
#     emoji_pattern = re.compile("["
#                            u"\U0001F600-\U0001F64F"  # emoticons
#                            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
#                            u"\U0001F680-\U0001F6FF"  # transport & map symbols
#                            u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
#                            u"\U00002702-\U000027B0"
#                            u"\U000024C2-\U0001F251"
#                            "]+", flags=re.UNICODE)
#     return emoji_pattern.sub(r'', string)
# df["text_no_emoji"] = df["text_lemmatized_with_pos"].apply(lambda text: remove_emoji(text))

In [46]:
def convert_emoticons(text):
    for emot in EMOTICONS:
        text = re.sub(u'(' + emot + ')', "_".join(EMOTICONS[emot].replace(",", "").split()), text)
    return text


text = "Hello :-) :-)"
convert_emoticons(text)

'Hello Happy_face_smiley Happy_face_smiley'

In [47]:
#TODO EMOJI replace with pytyhon emoji library

## Remove urls and HTML

In [48]:
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [49]:
def remove_html(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)


## Tokenizacja

In [50]:
from nltk.tokenize import TweetTokenizer

tweet_tokenizer = TweetTokenizer()


def tokenize_tweets(text):
    return tweet_tokenizer.tokenize(text)

df["text_tokenize"] = df["text_chat_conversion"].apply(lambda text: tokenize_tweets(text))
df["text_tokenize_preprocessed"] = df["text_preprocessed"].apply(lambda text: tokenize_tweets(text))

In [51]:
df.T

0  \
text                                 The cars drive, fast and erratically   
text_chat_conversion                 The cars drive, fast and erratically   
correct_spellings                     The cars drive fast and erratically   
text_punctation_remove                The cars drive fast and erratically   
text_lower                            the cars drive fast and erratically   
text_stopwords_removal                        cars drive fast erratically   
text_stemmed                                         car drive fast errat   
text_preprocessed                              car drive fast erratically   
text_lemmatized_with_pos               The car drive fast and erratically   
text_tokenize               [The, cars, drive, ,, fast, and, erratically]   
text_tokenize_preprocessed                [car, drive, fast, erratically]   

                                                     1  \
text                               the car drive slow?   
text_chat_conversion               the car drive slow?   
correct_spellings                   the car drive slow   
text_punctation_remove              the car drive slow   
text_lower                          the car drive slow   
text_stopwords_removal                  car drive slow   
text_stemmed                            car drive slow   
text_preprocessed                       car drive slow   
text_lemmatized_with_pos            the car drive slow   
text_tokenize               [the, car, drive, slow, ?]   
text_tokenize_preprocessed          [car, drive, slow]   

                                                                            2  
text                                 The bike ride very fast and erratically!  
text_chat_conversion                 The bike ride very fast and erratically!  
correct_spellings                     The bike ride very fast and erratically  
text_punctation_remove                The bike ride very fast and erratically  
text_lower                            the bike ride very fast and erratically  
text_stopwords_removal                             bike ride fast erratically  
text_stemmed                                             bike ride fast errat  
text_preprocessed                                  bike ride fast erratically  
text_lemmatized_with_pos              The bike ride very fast and erratically  
text_tokenize               [The, bike, ride, very, fast, and, erratically...  
text_tokenize_preprocessed                    [bike, ride, fast, erratically]

# ANALIZA DANYCH

## Bag of Words

In [52]:
vectorizer = CountVectorizer(lowercase=False)
vectorizer.fit(df["text_preprocessed"])
print(sorted(vectorizer.vocabulary_))
vector = vectorizer.transform(df["text_preprocessed"])

['bike', 'car', 'drive', 'erratically', 'fast', 'ride', 'slow']


In [54]:
print(vector.toarray())
pd.DataFrame(vector.toarray(),columns=sorted(vectorizer.vocabulary_))

[[0 1 1 1 1 0 0]
 [0 1 1 0 0 0 1]
 [1 0 0 1 1 1 0]]


bike  car  drive  erratically  fast  ride  slow
0     0    1      1            1     1     0     0
1     0    1      1            0     0     0     1
2     1    0      0            1     1     1     0

In [55]:
vectorizer.fit(df["text_punctation_remove"])
print(sorted(vectorizer.vocabulary_))
vector = vectorizer.transform(df["text_punctation_remove"])

['The', 'and', 'bike', 'car', 'cars', 'drive', 'erratically', 'fast', 'ride', 'slow', 'the', 'very']


In [56]:
print(vector.toarray())
pd.DataFrame(vector.toarray(),columns=sorted(vectorizer.vocabulary_))

[[1 1 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 1 1 0]
 [1 1 1 0 0 0 1 1 1 0 0 1]]


The  and  bike  car  cars  drive  erratically  fast  ride  slow  the  very
0    1    1     0    0     1      1            1     1     0     0    0     0
1    0    0     0    1     0      1            0     0     0     1    1     0
2    1    1     1    0     0      0            1     1     1     0    0     1

## TF-IDF

In [63]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(df["text_punctation_remove"])
feature_names = vectorizer.get_feature_names_out()
dense = vectors.todense()
denselist = dense.tolist()
df_one = pd.DataFrame(denselist, columns=feature_names)
df_one

and      bike       car      cars     drive  erratically      fast  \
0  0.397402  0.000000  0.000000  0.522535  0.397402     0.397402  0.397402   
1  0.000000  0.000000  0.584483  0.000000  0.444514     0.000000  0.000000   
2  0.337295  0.443503  0.000000  0.000000  0.000000     0.337295  0.337295   

       ride      slow       the      very  
0  0.000000  0.000000  0.308618  0.000000  
1  0.000000  0.584483  0.345205  0.000000  
2  0.443503  0.000000  0.261940  0.443503

In [59]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(df["text_preprocessed"])
feature_names = vectorizer.get_feature_names_out()
dense = vectors.todense()
denselist = dense.tolist()
df_one = pd.DataFrame(denselist, columns=feature_names)
df_one

bike       car     drive  erratically      fast      ride      slow
0  0.000000  0.500000  0.500000     0.500000  0.500000  0.000000  0.000000
1  0.000000  0.517856  0.517856     0.000000  0.000000  0.000000  0.680919
2  0.562829  0.000000  0.000000     0.428046  0.428046  0.562829  0.000000

## Podobieństwo Cosinusów


In [84]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

# Create a matrix to represent the corpus
X = CountVectorizer().fit_transform(df['text_preprocessed']).toarray()

cos = cosine_similarity([X[0,:],X[1,:],X[2,:]])

In [85]:
cos

array([[1.        , 0.57735027, 0.5       ],
       [0.57735027, 1.        , 0.        ],
       [0.5       , 0.        , 1.        ]])